uploads = []
outputs = []

[[generated]]
id = "gbpFxS5qJHvUiPJf0Oygb"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "rewards app icon"

[[generated]]
id = "664C1m6TrvlMNZW2Eq0ce"
uri = "file://artifacts/mobile/assets/images/pixel-flow-banner.png"
type = "image"
title = "pixel flow game banner"

[[generated]]
id = "mIeErxfBUqpeNgHY1Krqh"
uri = "file://artifacts/mobile/assets/images/empty-tasks.png"
type = "image"
title = "empty tasks folder illustration"
